# coding: utf-8

"""
    APIFlask

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from flatland.integrations.interactiveai.event_api.models.metadata_schema_railway import MetadataSchemaRailway


class EventOut(BaseModel):
    """
    EventOut
    """  # noqa: E501
    criticality: Optional[StrictStr] = None
    data: Optional[MetadataSchemaRailway] = None
    description: Optional[StrictStr] = None
    end_date: Optional[datetime] = None
    id: Optional[StrictInt] = None
    id_event: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = None
    of_uid: Optional[StrictStr] = None
    parent_event_id: Optional[StrictStr] = None
    start_date: Optional[datetime] = None
    title: Optional[StrictStr] = None
    use_case: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["criticality", "data", "description", "end_date", "id", "id_event", "is_active", "of_uid", "parent_event_id",
                                         "start_date", "title", "use_case"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if parent_event_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_event_id is None and "parent_event_id" in self.model_fields_set:
            _dict['parent_event_id'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "criticality": obj.get("criticality"),
            "data": MetadataSchemaRailway.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "description": obj.get("description"),
            "end_date": obj.get("end_date"),
            "id": obj.get("id"),
            "id_event": obj.get("id_event"),
            "is_active": obj.get("is_active"),
            "of_uid": obj.get("of_uid"),
            "parent_event_id": obj.get("parent_event_id"),
            "start_date": obj.get("start_date"),
            "title": obj.get("title"),
            "use_case": obj.get("use_case")
        })
        return _obj
