name: Main

on:
    workflow_dispatch:
    schedule:
        -   cron: '30 5 * * *'
    push:
        branches: [ "main" ]

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        if: ${{ false }}  # disabled for now, hasn't run in a while resulting in countless issues
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run lint checks
                run: tox run -e flake8

    test:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.10", "3.11", "3.12" ]
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Download episodes
                run: |
                    wget "https://data.flatland.cloud/trajectories/FLATLAND_BENCHMARK_EPISODES_FOLDER.zip" -O FLATLAND_BENCHMARK_EPISODES_FOLDER.zip
                    mkdir -p episodes
                    unzip FLATLAND_BENCHMARK_EPISODES_FOLDER -d episodes
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run tests
                run: tox

    notebooks:
        if: ${{ false }}  # disabled for now, some need custom kernel
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run notebooks
                run: tox run -e notebooks

    examples:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run examples
                run: tox run -e examples

    profiling:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run profiling
                run: tox run -e profiling

    benchmarks:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Download episodes
                run: |
                    wget "https://data.flatland.cloud/trajectories/FLATLAND_BENCHMARK_EPISODES_FOLDER.zip" -O FLATLAND_BENCHMARK_EPISODES_FOLDER.zip
                    mkdir -p episodes
                    unzip FLATLAND_BENCHMARK_EPISODES_FOLDER -d episodes
                working-directory: ${{ github.workspace }}
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Run benchmarks
                run: tox run -e benchmarks

    publish:
        if: ${{ false }}  # disabled until decided when it should run exactly
        runs-on: ubuntu-22.04
        needs: [ test, examples ]
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.10"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Build new package
                run: tox run -e build
            -   name: Publish distribution to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    password: ${{ secrets.PYPI_API_TOKEN }}
            -   name: Archive package
                uses: actions/upload-artifact@v4
                with:
                    name: python-package
                    path: dist/
