name: Publish package to PyPI

env:
    # DEPENDENCY SWITCH:
    flatland-baselines-ref: main
    flatland-benchmarks-episodes-url: "https://github.com/flatland-association/flatland-scenarios/raw/refs/heads/main/trajectories/FLATLAND_BENCHMARK_EPISODES_FOLDER_v5.zip"

on:
    pull_request:
        branches: [ "main" ]
        types: [ "closed" ]

jobs:
    test:
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') }}
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        steps:
            -   name: Inspect disk
                run: |
                    df -h
                    docker system df
            # https://stackoverflow.com/questions/30604846/docker-complains-about-no-space-left-on-device-how-to-clean-up
            -   name: Prune docker system
                run: |
                    docker system prune --all --force
            # https://www.dzombak.com/blog/2024/09/freeing-disk-space-on-github-actions-runners/
            -   name: Free disk space
                run: |
                    curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
            -   name: Inspect disk again
                run: |
                    df -h
                    docker system df
            -   name: Install ffmpeg
                run: |
                    sudo apt-get update
                    sudo apt-get -y install ffmpeg
            -   uses: actions/checkout@v6
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v6
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Download episodes
                run: |
                    wget "${{ env.flatland-benchmarks-episodes-url }}" -O FLATLAND_BENCHMARK_EPISODES_FOLDER.zip
                    mkdir -p episodes
                    unzip FLATLAND_BENCHMARK_EPISODES_FOLDER -d episodes
            -   name: Clone flatland-baselines
                uses: actions/checkout@v6
                with:
                    repository: flatland-association/flatland-baselines
                    ref: ${{ env.flatland-baselines-ref }}
                    path: flatland-baselines
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install tox tox-gh-actions
            -   name: Run tests
                run: tox -e py${{ matrix.python-version }},py${{ matrix.python-version }}-verify-install
            -   name: Check disk space
                run: df . -h

    publish:
        runs-on: ubuntu-22.04
        needs: [ test ]
        permissions:
            contents: write
        outputs:
            version_tag: ${{ steps.build-version-tag.outputs.VERSION_TAG }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
                with:
                    fetch-depth: 0
            -   name: Set up Python
                uses: actions/setup-python@v6
                with:
                    python-version: "3.13"
            -   name: Install tox
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions
            -   name: Build version tag
                id: build-version-tag
                run: |
                    VERSION=$(echo "$GITHUB_HEAD_REF" | sed 's/release\///')
                    echo "VERSION_TAG=v$VERSION" >> "$GITHUB_OUTPUT"
            -   name: Tag commit with version
                env:
                    VERSION_TAG: ${{ steps.build-version-tag.outputs.VERSION_TAG }}
                run: git tag "$VERSION_TAG"
            -   name: Build new package
                run: tox run -e build
            -   name: Publish package to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    password: ${{ secrets.PYPI_API_TOKEN }}
            -   name: Push version tag
                env:
                    VERSION_TAG: ${{ steps.build-version-tag.outputs.VERSION_TAG }}
                run: git push origin "$VERSION_TAG"
            -   name: Archive package
                uses: actions/upload-artifact@v6
                with:
                    name: python-package
                    path: dist/

    docker-publish:
        runs-on: ubuntu-22.04
        needs: [ publish ]
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.12" ]
                variant:
                    -   name: default
                        with-ml: "false"
                        tag-suffix: ""
                    -   name: ml
                        with-ml: "true"
                        tag-suffix: "-ml"
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build image name
                id: image-name
                run: echo "IMAGE_NAME=$(echo '${{ env.REGISTRY }}/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
            -   name: Build and push image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    build-args: |
                        PYTHON_VERSION=${{ matrix.python-version }}
                        WITH_ML=${{ matrix.variant.with-ml }}
                        FLATLAND_RL_REF=${{ needs.publish.outputs.version_tag }}
                    no-cache: true
                    push: true
                    tags: ${{ steps.image-name.outputs.IMAGE_NAME }}:${{ needs.publish.outputs.version_tag }}-py${{ matrix.python-version }}${{ matrix.variant.tag-suffix }}
